### ISSUE TITLE
/_matrix/client/r0/pushrules/ giving 404

### ISSUE THREAD

**Issue by qalqi** [social-network/conduit#6]
GET http://localhost:6167/_matrix/client/r0/pushrules/ 404 (Not Found)
Getting push rules failed M_NOT_FOUND: M_NOT_FOUND: PushRules event not found.
<img width="904" alt="Screen Shot 2021-03-12 at 9 47 50 PM" src="https://user-images.githubusercontent.com/1781048/111029455-a9f39700-8422-11eb-98a8-27406c924379.png">

**Comment by qalqi** [comment]
@DevinR528 can you fix this endpoint /_matrix/client/r0/pushrules/ in develop branch

**Comment by qalqi** [comment]
in master branch,  /_matrix/client/r0/pushrules/ is giving 200 this get.json
https://gist.github.com/qalqi/e4b48ef42898402d5723aa78be4cafe0

**Comment by qalqi** [comment]
@andor0

**Comment by DevinR528** [comment]
Hmm... I'm not entirely sure why that isn't working. You are using a logged-in user, that has registered an account, with a new DB (it may be that deserialization is failing somewhat silently)? I can try to reproduce it later today or tomorrow.

**Comment by andor0** [comment]
@DevinR528, this isn't relevant already.
Was a problem with data in the database. We did drop the database because it had not critical data for us.

**Comment by qalqi** [comment]
this issue occurs only in m.login.token flow. commit https://github.com/social-network/conduit/commit/d9f37b294047ef4271e1324c57224896df314afc fixes it
Thanks @andor0
